var weapon_list = {
	"club":         {name: 'club',         cost: '1 sp', damage: '1d4 bl', weight: '2 lb.',  category: 'simple', attrs: ['light'], uses: [{what: 'hand', amt: 1}],},
	"dagger":       {name: 'dagger',       cost: '2 gp', damage: '1d4 pi', weight: '1 lb.',  category: 'simple', ranged: true, attrs: ['finesse', 'light', 'thrown'], range: {min: 20, max: 60}, uses: [{what: 'hand', amt: 1}],},
	"dagger":       {name: 'dagger',       cost: '2 gp', damage: '1d4 pi', weight: '1 lb.',  category: 'simple', attrs: ['finesse', 'light', 'thrown'], uses: [{what: 'hand', amt: 1}],},
	"greatclub":    {name: 'greatclub',    cost: '2 sp', damage: '1d8 bl', weight: '10 lb.', category: 'simple', attrs: ['twohanded'], uses: [{what: 'hand', amt: 2}],},
	"handaxe":      {name: 'handaxe',      cost: '5 gp', damage: '1d6 sl', weight: '2 lb.',  category: 'simple', attrs: ['light', 'thrown'], range: {min: 20, max: 60}, uses: [{what: 'hand', amt: 1}],},
	"javelin":      {name: 'javelin',      cost: '5 sp', damage: '1d6 pi', weight: '2 lb.',  category: 'simple', ranged: true, attrs: ['thrown'], range: {min: 30, max: 120}, uses: [{what: 'hand', amt: 1}],},
	"javelin":      {name: 'javelin',      cost: '5 sp', damage: '1d6 pi', weight: '2 lb.',  category: 'simple', attrs: ['thrown'], uses: [{what: 'hand', amt: 1}],},
	"light hammer": {name: 'light hammer', cost: '2 gp', damage: '1d4 bl', weight: '2 lb.',  category: 'simple', ranged: true, attrs: ['light', 'thrown'], range: {min: 20, max: 60}, uses: [{what: 'hand', amt: 1}],},
	"light hammer": {name: 'light hammer', cost: '2 gp', damage: '1d4 bl', weight: '2 lb.',  category: 'simple', attrs: ['light', 'thrown'], uses: [{what: 'hand', amt: 1}],},
	"mace":         {name: 'mace',         cost: '5 gp', damage: '1d6 bl', weight: '4 lb.',  category: 'simple', attrs: ['none'], uses: [{what: 'hand', amt: 1}],},
	"quarterstaff": {name: 'quarterstaff', cost: '2 sp', damage: '1d6 bl', weight: '4 lb.',  category: 'simple', attrs: ['versatile'], uses: [{what: 'hand', amt: 1}],},
	"quarterstaff": {name: 'quarterstaff', cost: '2 sp', damage: '1d8 bl', weight: '4 lb.',  category: 'simple', attrs: ['versatile'], uses: [{what: 'hand', amt: 2}],},
	"sickle":       {name: 'sickle',       cost: '1 gp', damage: '1d4 sl', weight: '2 lb.',  category: 'simple', attrs: ['light'], uses: [{what: 'hand', amt: 1}],},
	"spear":        {name: 'spear',        cost: '1 gp', damage: '1d6 pi', weight: '3 lb.',  category: 'simple', ranged: true, attrs: ['thrown', 'versatile'], range: {min: 20, max: 60}, uses: [{what: 'hand', amt: 1}],},
	"spear":        {name: 'spear',        cost: '1 gp', damage: '1d6 pi', weight: '3 lb.',  category: 'simple', attrs: ['thrown', 'versatile'], uses: [{what: 'hand', amt: 1}],},
	"spear":        {name: 'spear',        cost: '1 gp', damage: '1d8 pi', weight: '3 lb.',  category: 'simple', attrs: ['thrown', 'versatile'], uses: [{what: 'hand', amt: 2}],},

	"light crossbow":{name: 'light crossbow', cost: '25 gp', damage: '1d8 pi', weight: '5 lb.',   category: 'simple', ranged: true, attrs: ['ammunition', 'loading', 'twohanded'], range: {min: 80, max: 320}, uses: [{what: 'hand', amt: 2}],},
	"dart":          {name: 'dart',           cost: '5 cp',  damage: '1d4 pi', weight: '1/4 lb.', category: 'simple', ranged: true, attrs: ['finesse', 'thrown'], range: {min: 20, max: 60}, uses: [{what: 'hand', amt: 1}],},
	"dart":          {name: 'dart',           cost: '5 cp',  damage: '1d4 pi', weight: '1/4 lb.', category: 'simple', attrs: ['finesse', 'thrown'], uses: [{what: 'hand', amt: 1}],},
	"shortbow":      {name: 'shortbow',       cost: '25 gp', damage: '1d6 pi', weight: '2 lb.',   category: 'simple', ranged: true, attrs: ['ammunition', 'twohanded'], range: {min: 80, max: 320}, , uses: [{what: 'hand', amt: 1}],},
	"sling":         {name: 'sling',          cost: '1 sp',  damage: '1d4 bl', weight: '0 lb.',   category: 'simple', ranged: true, attrs: ['ammunition'], range: {min: 30, max: 120}, uses: [{what: 'hand', amt: 1}],},

	"battleaxe":  {name: 'battleaxe',   cost: '10 gp', damage: '1d8 sl',  weight: '4 lb.',  category: 'martial', attrs: ['versatile'], uses: [{what: 'hand', amt: 1}],},
	"battleaxe":  {name: 'battleaxe',   cost: '10 gp', damage: '1d10 sl', weight: '4 lb.',  category: 'martial', attrs: ['versatile'], uses: [{what: 'hand', amt: 2}],},
	"flail":      {name: 'flail',       cost: '10 gp', damage: '1d8 bl',  weight: '2 lb.',  category: 'martial', attrs: ['none'], uses: [{what: 'hand', amt: 1}],},
	"glaive":     {name: 'glaive',      cost: '20 gp', damage: '1d10 sl', weight: '6 lb.',  category: 'martial', attrs: ['heavy', 'reach', 'twohanded'], uses: [{what: 'hand', amt: 2}],},
	"greataxe":   {name: 'greataxe',    cost: '30 gp', damage: '1d12 sl', weight: '7 lb.',  category: 'martial', attrs: ['heavy', 'twohanded'], uses: [{what: 'hand', amt: 2}],},
	"greatsword": {name: 'greatsword',  cost: '50 gp', damage: '2d6 sl',  weight: '6 lb.',  category: 'martial', attrs: ['heavy', 'twohanded'], uses: [{what: 'hand', amt: 2}],},
	"halberd":    {name: 'halberd',     cost: '20 gp', damage: '1d10 sl', weight: '6 lb.',  category: 'martial', attrs: ['heavy', 'reach', 'twohanded'], uses: [{what: 'hand', amt: 2}],},
	"lance":      {name: 'lance',       cost: '10 gp', damage: '1d12 pi', weight: '6 lb.',  category: 'martial', attrs: ['reach', 'special'], uses: [{what: 'hand', amt: 1}],},
	"longsword":  {name: 'longsword',   cost: '15 gp', damage: '1d8 sl',  weight: '3 lb.',  category: 'martial', attrs: ['versatile'], uses: [{what: 'hand', amt: 1}],},
	"longsword":  {name: 'longsword',   cost: '15 gp', damage: '1d10 sl', weight: '3 lb.',  category: 'martial', attrs: ['versatile'], uses: [{what: 'hand', amt: 2}],},
	"maul":       {name: 'maul',        cost: '10 gp', damage: '2d6 bl',  weight: '10 lb.', category: 'martial', attrs: ['heavy', 'twohanded'], uses: [{what: 'hand', amt: 2}],},
	"morningstar":{name: 'morningstar', cost: '15 gp', damage: '1d8 pi',  weight: '4 lb.',  category: 'martial', attrs: ['none'], uses: [{what: 'hand', amt: 1}],},
	"pike":       {name: 'pike',        cost: '5 gp',  damage: '1d10 pi', weight: '18 lb.', category: 'martial', attrs: ['heavy', 'reach', 'twohanded'], uses: [{what: 'hand', amt: 2}],},
	"rapier":     {name: 'rapier',      cost: '25 gp', damage: '1d8 pi',  weight: '2 lb.',  category: 'martial', attrs: ['finesse'], uses: [{what: 'hand', amt: 1}],},
	"scimitar":   {name: 'scimitar',    cost: '25 gp', damage: '1d6 sl',  weight: '3 lb.',  category: 'martial', attrs: ['finesse' 'light'], uses: [{what: 'hand', amt: 1}],},
	"shortsword": {name: 'shortsword',  cost: '10 gp', damage: '1d6 pi',  weight: '2 lb.',  category: 'martial', attrs: ['finesse', 'light'], uses: [{what: 'hand', amt: 1}],},
	"trident":    {name: 'trident',     cost: '5 gp',  damage: '1d6 pi',  weight: '4 lb.',  category: 'martial', ranged: true, attrs: ['thrown', 'versatile'], range: {min: 20, max: 60}, uses: [{what: 'hand', amt: 1}],},
	"trident":    {name: 'trident',     cost: '5 gp',  damage: '1d6 pi',  weight: '4 lb.',  category: 'martial', attrs: ['thrown', 'versatile'], uses: [{what: 'hand', amt: 1}],},
	"trident":    {name: 'trident',     cost: '5 gp',  damage: '1d8 pi',  weight: '4 lb.',  category: 'martial', attrs: ['thrown', 'versatile'], uses: [{what: 'hand', amt: 2}],},
	"war pick":   {name: 'war pick',    cost: '5 gp',  damage: '1d8 pi',  weight: '2 lb.',  category: 'martial', attrs: ['none'], uses: [{what: 'hand', amt: 1}],},
	"warhammer":  {name: 'warhammer',   cost: '15 gp', damage: '1d8 bl',  weight: '2 lb.',  category: 'martial', attrs: ['versatile'], uses: [{what: 'hand', amt: 1}],},
	"warhammer":  {name: 'warhammer',   cost: '15 gp', damage: '1d10 bl', weight: '2 lb.',  category: 'martial', attrs: ['versatile'], uses: [{what: 'hand', amt: 2}],},
	"whip":       {name: 'whip',        cost: '2 gp',  damage: '1d4 sl',  weight: '3 lb.',  category: 'martial', attrs: ['finesse', 'reach'], uses: [{what: 'hand', amt: 1}],},

	"blowgun":        {name: 'blowgun',        cost: '10 gp', damage: '1 pi',    weight: '1 lb.',  category: 'martial', ranged: true, attrs: ['ammunition', 'loading'], range: {min: 25, max: 100}, uses: [{what: 'hand', amt: 1}],},
	"hand crossbow":  {name: 'hand crossbow',  cost: '75 gp', damage: '1d6 pi',  weight: '3 lb.',  category: 'martial', ranged: true, attrs: ['ammunition', 'light', 'loading'], range: {min: 30, max: 120}, uses: [{what: 'hand', amt: 1}],},
	"heavy crossbow": {name: 'heavy crossbow', cost: '50 gp', damage: '1d10 pi', weight: '18 lb.', category: 'martial', ranged: true, attrs: ['ammunition', 'heavy', 'loading', 'twohanded'], range: {min: 100, max: 400}, uses: [{what: 'hand', amt: 2}],},
	"longbow":        {name: 'longbow',        cost: '50 gp', damage: '1d8 pi',  weight: '2 lb.',  category: 'martial', ranged: true, attrs: ['ammunition', 'heavy', 'twohanded'], range: {min: 150, max: 600}, uses: [{what: 'hand', amt: 2}],},
	"net":            {name: 'net',            cost: '1 gp',  damage: '0d4 fo',  weight: '3 lb.',  category: 'martial', ranged: true, attrs: ['special', 'thrown'], range: {min: 5, max: 15}, uses: [{what: 'hand', amt: 1}],},
};

if(module && module.exports) module.exports = weapon_list;
